name: Android CI

on:
  push:
    branches:
      - master
      - dev
      - feature/*
    tags:
      - 'v*'
  pull_request:
    branches:
      - dev
      - master
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run connected Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Count executed Android tests
        run: |
          count=$(find app/build/outputs/androidTest-results/connected -name "*.xml" -exec grep -c "<testcase" {} \; | awk '{sum+=$1} END {print sum}')
          echo "Total testcases: $count"
          if [ "$count" -lt 1 ]; then
            echo " Недостаточно тестов: найдено $count, требуется минимум 1"
            exit 1
          fi

      - name: Upload Android test reports (JUnit XML)
        uses: actions/upload-artifact@v4
        with:
          name: android-junit-reports
          path: app/build/outputs/androidTest-results/connected

      - name: Upload Android test HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: android-html-reports
          path: app/build/reports/androidTests